version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - HF_API_TOKEN=${HF_API_TOKEN}
      - RENDERING_ENGINE=${RENDERING_ENGINE:-REPLICATE}
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    name: ai-comic-factory 